apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-deploy-green
  labels:
    app: sample-api-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-api-green
  template:
    metadata:
      labels:
        app: sample-api-green
    spec:
      containers:
        - name: sample-api
          image: youodf/sample-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
