[package]
name = "sample-job"
version = "0.1.0"
authors = ["yodai.a.kishimoto <yodai.a.kishimoto@rakuten.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
