apiVersion: v1
kind: Pod
metadata:
  name: sample-api-deploy
  labels:
    app: sample-api
spec:
  containers:
    - name: sample-api
      image: youodf/sample-api:1.0.0
      ports:
        - containerPort: 8000
