apiVersion: v1
kind: Pod
metadata:
  name: sample-api-pod
  labels:
    app: sample-api
spec:
  containers:
    - name: sample-api
      image: youodf/sample-api:1.0.0
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
